name: publish

on:
  push:
    branches:
      - main

jobs:
  rust:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install CI tools
        run: |
          apt-get update
          apt-get install -y curl jq build-essential

      - uses: dtolnay/rust-toolchain@stable

      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
          cargo install mdbook-linkcheck
          cargo install mdbook-alerts

      - uses: extractions/setup-just@v2

      - name: Build Book
        run: just build

      - name: Deploy to website
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./book/html/
          server-dir: ./data/rust-data-analysis/
          state-name: ../.ftp-deploy-sync-state.json